import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const solaimanLipi = localFont({
  src: "./fonts/SolaimanLipi.woff",
  variable: "--font-solaimanLipi",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Ebdresults Thumbnail Create Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${solaimanLipi.variable} antialiased`} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
